# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bfsCpp <- function(S, G) {
    invisible(.Call(`_mcgraph_bfsCpp`, S, G))
}

frgCpp <- function(P, A, iter = 500L, W = 10.0, L = 10.0, temp_prop = 0.1, force_prop = 0.5, quench_prop = 0.9, simmering_prop = 0.05) {
    invisible(.Call(`_mcgraph_frgCpp`, P, A, iter, W, L, temp_prop, force_prop, quench_prop, simmering_prop))
}

graph2dataCpp <- function(D, A, n = 200L, iter = 15L, val = 100.0, sd = 2.0, prop = 0.1, noise = 1.0, init = FALSE) {
    invisible(.Call(`_mcgraph_graph2dataCpp`, D, A, n, iter, val, sd, prop, noise, init))
}

lvsCpp <- function(A, RS, cor_mat, D, rs = 0.04, k = 5L) {
    invisible(.Call(`_mcgraph_lvsCpp`, A, RS, cor_mat, D, rs, k))
}

